# Generated by Django 4.0.4 on 2022-05-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google_sheet',
            fields=[
                ('id', models.SmallIntegerField(db_index=True, default='None', primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(default='None')),
                ('price_usd', models.FloatField(default='None')),
                ('delivery_time', models.DateField(blank=True, default='None')),
                ('price_rub', models.FloatField(default='None')),
            ],
            options={
                'verbose_name': 'Google sheet',
                'verbose_name_plural': 'Google sheets',
                'ordering': ('-id',),
            },
        ),
    ]
